FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app/backend
RUN pip install --upgrade pip



COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . /app/backend/

EXPOSE 8000

COPY . ./
