FROM python:3.11.7-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /backend 


RUN pip install --upgrade pip
COPY ./requirements.txt .


RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

