name: Check
on: 
    pull_request:
        branches: dev
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Change Directory
            run: cd .\frontend\
          - name: Install deps
            run: npm ci
          - name: ESLint
            run: npm run lint
    test:
      needs: [lint]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Change Directory
            run: cd .\frontend\
          - name: Install deps
            run: npm ci
          - name: Test
            run: npm run test
