name: Check
on: 
    push:
        branches: [ dev, git_actions ]
    pull_request:
        branches: [ dev ]
jobs:
    lint:
      runs-on: windows-latest

      strategy:
        fail-fast: false
        matrix:
          node-version: [ 16.x, 18.x ]

      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}

          - name: Install deps
            working-directory: ./frontend
            run: |
              del package-lock.json
              npm install

          - name: ESLint
            working-directory: ./frontend
            run: npm run lint

    test:

      needs: [lint]

      runs-on: windows-latest

      strategy:
        fail-fast: false
        matrix:
          node-version: [ 16.x, 18.x ]

      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node-version }}

          - name: Install deps
            working-directory: ./frontend
            run: |
              del package-lock.json
              npm install

          - name: Test
            working-directory: ./frontend
            run: npm run test
